[package]
name = "expanse"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.5", features = ["derive"] }
env_logger = "0.11.11"
log = "0.4.33"
rust-htslib = { version = "1.0.1", features = ["s3", "gcs"] }
url = "2.5"

[profile.release]
codegen-units = 1
lto = "fat"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "irr"
harness = false
